### ISSUE TITLE
Unclear how users can get support

### ISSUE THREAD

**Issue by RichardLitt** [SimonGreenhill/treemaker#10]
Are GitHub issues for support suggested? Is there support offered for users of this software? Should they email you? Are contributions encouraged, or is the 'email me first' paragraph meant to be discouraging? 

The BSD3 license offers no liability or warranty, and says the software is provided "as is", which means that without explicit statements about potential help to support, it can be implied to not exist. Something to the opposite effect - a paragraph saying: "We're happy to look at GitHub issues or respond to emails" would be great. This will probably not be a high intensity, high traffic tool, so I don't expect this to ever lead to maintainer burnout.

**Comment by RichardLitt** [comment]
Crossref: https://github.com/openjournals/joss-reviews/issues/1040

**Comment by SimonGreenhill** [comment]
Would a line in the README.md work e.g.:

```
## Need help?

Please create an issue in `treemaker`'s [Github Issues list](https://github.com/SimonGreenhill/treemaker/issues/) and I will try help you as soon as I can.

```

**Comment by RichardLitt** [comment]
Yep! Just want to make sure this is explicit.

**Comment by RichardLitt** [comment]
Or, more formally

```md
## Support

For questions on how to use or update this, feel free to open an issue. I'll get to it as soon as I can. 
```

**Comment by SimonGreenhill** [comment]
Great, thanks -- added in https://github.com/SimonGreenhill/treemaker/commit/8dcf2b589369a208654a018609275c8a979a3e83
