### ISSUE TITLE
Nexus reference is missing DOI

### ISSUE THREAD

**Issue by RichardLitt** [SimonGreenhill/treemaker#11]
I was unable to find DOIs for the SIL book and the 1975 article, but the 1997 article on Nexus [certainly has one](https://search.crossref.org/?q=Nexus%3A+An+Extensible+File+Format), which should be added. 

https://academic.oup.com/sysbio/article/46/4/590/1629695

https://doi.org/10.1093/sysbio/46.4.590

**Comment by RichardLitt** [comment]
Ah. I missed [this commit](https://github.com/SimonGreenhill/treemaker/commit/f4e320e31d6a1b5072ce40ed8cb3fb94a53843a8). Can you render these .bib changes to the .pdf? They're not in the paper, at the moment.

**Comment by RichardLitt** [comment]
Crossref: https://github.com/openjournals/joss-reviews/issues/1040

**Comment by SimonGreenhill** [comment]
I've rebuilt the paper in https://github.com/SimonGreenhill/treemaker/commit/df82c050ae241469bcc49ed300a3a059e20cd999 and whedon's trying to rebuild it [here](https://github.com/openjournals/joss-reviews/issues/1040)

**Comment by RichardLitt** [comment]
Awesome! Thanks!
