### ISSUE TITLE
Increase test coverage to 100%

### ISSUE THREAD

**Issue by RichardLitt** [SimonGreenhill/treemaker#12]
You're one test away from 100% code coverage. I think it might be worth adding another test. :) 

https://coveralls.io/builds/19852503/source?filename=treemaker/treemaker.py#L210

Crossref openjournals/joss-reviews#1040

**Comment by SimonGreenhill** [comment]
Done in https://github.com/SimonGreenhill/treemaker/commit/78c354c97dba64afde893b976ede76d0d08851b1 and https://github.com/SimonGreenhill/treemaker/commit/ace4ed06c7a86c85593f728e98242372d088ea8d

**Comment by RichardLitt** [comment]
Thanks! Above and beyond.
