### ISSUE TITLE
Paper: references missing DOIs

### ISSUE THREAD

**Issue by deniederhut** [SimonGreenhill/treemaker#2]
There are two papers in the references section (the one on the Nexus format, and the one on the Papuan New Guinea languages) that are missing DOIs. It looks like Ethnologue does not have a persistent identifier associated with its software product, so it might be nice to have a URL for it.

xref https://github.com/openjournals/joss-reviews/issues/1040

**Comment by SimonGreenhill** [comment]
Thanks, added [here](https://github.com/SimonGreenhill/treemaker/commit/f4e320e31d6a1b5072ce40ed8cb3fb94a53843a8)
