### ISSUE TITLE
Change GitHub description

### ISSUE THREAD

**Issue by RichardLitt** [SimonGreenhill/treemaker#6]
Currently, the description for this repository reads: 

> A Python tool for constructing a newick formatted tree from a set of classifications. 

I think it should read:

> A Python library for creating a Newick formatted tree from a set of classification strings

Likewise, in the README, "python" is not properly capitalized in the first line.

**Comment by SimonGreenhill** [comment]
Both fixed, thanks!

**Comment by RichardLitt** [comment]
No prob.

Crossref: https://github.com/openjournals/joss-reviews/issues/1040
