### ISSUE TITLE
Update basic usage block

### ISSUE THREAD

**Issue by RichardLitt** [SimonGreenhill/treemaker#7]
It should printout:

```sh
> treemaker
usage: treemaker [-h] [-o OUTPUT] [-m {nexus,newick}] input
```

Instead of 

```sh
> treemaker
usage: treemaker [-h] input
```

The error which also is printed can probably be left out: `treemaker: error: too few arguments`.

**Comment by SimonGreenhill** [comment]
oops. Fixed in https://github.com/SimonGreenhill/treemaker/commit/58929ea09d5ca6fd9c79753b29766548d04bee6f

**Comment by RichardLitt** [comment]
Thanks!

Crossref: https://github.com/openjournals/joss-reviews/issues/1040
