### ISSUE TITLE
Lines 63 and 48 in the README are missing semicolons

### ISSUE THREAD

**Issue by RichardLitt** [SimonGreenhill/treemaker#8]
The `treemaker` command prints semicolons, which aren't in the documentation. I think it'd be worth adding them.

```sh
> treemaker example
(LangD,(LangA,LangB),LangC);
```

I can also make a PR, but am unsure if that's frowned upon by an editor.

**Comment by SimonGreenhill** [comment]
Thanks @RichardLitt  -- fixed in https://github.com/SimonGreenhill/treemaker/commit/adacc853c654ae395913a5299fc20483c2dea68d

**Comment by RichardLitt** [comment]
Thanks!

Crossref: https://github.com/openjournals/joss-reviews/issues/1040
