### ISSUE TITLE
Add section to README on how to run the tests

### ISSUE THREAD

**Issue by RichardLitt** [SimonGreenhill/treemaker#9]
Something as simple as:

### Tests

To run the tests, run:

```sh
> python treemaker/test_treemaker.py
........................................
----------------------------------------------------------------------
Ran 40 tests in 0.016s

OK
```

**Comment by SimonGreenhill** [comment]
Done in https://github.com/SimonGreenhill/treemaker/commit/de0c3ee661a2dfca3328a6c8dd4f63adbd43dc0c

**Comment by RichardLitt** [comment]
Thanks!

Crossref: https://github.com/openjournals/joss-reviews/issues/1040
